### ISSUE TITLE
1.15.2 no purifier?

### ISSUE THREAD

**Issue by tealtoxic** [Caltinor/Corrupted-Land#4]
as the title says. nice mod :)

**Comment by Caltinor** [comment]
Just wanted to acknowledge this issue and provide you an updated.  One, the 1.15 version is maintained by BlueDuckYT, whom I spoke to about this.  Since the purifier is planned to have some major updating (fixing it breaking on overuse, better textures, and JEI integration) they want to wait until I have made the update on the 1.16 version before updating.  At this time I do not know when I will get to that specific project.  I have some IRL demands right now that take up most of my time.  I will update here as progress is made.

**Comment by tealtoxic** [comment]
noted. thank you.

**Comment by Caltinor** [comment]
Support for 1.15 has been dropped.  Even though the Purifier was updated, the author decided not to maintain it.
